# =============================================================================
# 00_config.R
# Portable path configuration — LRP Demand Analysis
#
# HOW TO USE:
#   Open analysis.Rproj in RStudio (once). After that, add this one line
#   to the top of every script:
#       source(here::here("codes", "00_config.R"))
#
# RULE: input_ variables = read only.  output_ variables = write here.
# =============================================================================
if (!requireNamespace("here", quietly = TRUE)) install.packages("here")
library(here)

# =============================================================================
# INPUT paths  (read only — never overwrite raw data)
# =============================================================================

# Annual LRP Summary of Business files (2005-2026)
input_lrp_annual  <- here("data", "raw", "lrp_annual")

# Compiled cattle panels (feeder_cattle.csv, fed_cattle.csv)
input_raw         <- here("data", "raw")

# CME futures continuous series
input_futures     <- here("data", "raw", "futures")

# LRP-options matched data (with IV)
input_options     <- here("data", "raw", "options")

# Policy-level hedge gap data (ZF = feeder, OK = fed)
input_gap         <- here("data", "raw", "gap")

# PCA scores from option smile
input_pca         <- here("data", "raw", "pca")

# External data (downloaded separately — see codes/01_build/04_download_drought.py)
input_drought     <- here("data", "external", "drought")    # USDM county-weekly
input_cash        <- here("data", "external", "cash_price") # USDA AMS 5-area cash
input_cot         <- here("data", "external", "cot")        # CFTC COT

# =============================================================================
# INPUT file shortcuts
# =============================================================================

file_feeder         <- here("data", "raw", "feeder_cattle.csv")
file_fed            <- here("data", "raw", "fed_cattle.csv")
file_county_weekly  <- here("data", "raw", "county_weekly_metrics_2015_2024.csv")
file_gf             <- here("data", "raw", "futures",  "GF.csv")
file_le             <- here("data", "raw", "futures",  "LE.csv")
file_matched5       <- here("data", "raw", "options",  "matched_5.csv")
file_matched_iv     <- here("data", "raw", "options",  "matched_with_iv.csv")
file_matched_2225   <- here("data", "raw", "options",  "11_5_22to25_matched_futures.csv")
file_zf_gap         <- here("data", "raw", "gap",      "ZF_indemn_amt.xlsx")
file_ok_gap         <- here("data", "raw", "gap",      "OK_indemn_amt.xlsx")
file_pca            <- here("data", "raw", "pca",      "pca_cattle_scores_simplified.csv")
# Raw USDM download (input to code04a)
file_drought_raw    <- here("data", "raw",      "drought_bycounty.csv")
# Processed output of code04a (input to code04_merge_drought.R)
file_drought        <- here("data", "external", "drought", "usdm_county_weekly.csv")
file_cash_price     <- here("data", "external", "cash_price", "cash_cattle_5area.csv")

# =============================================================================
# OUTPUT paths  (scripts write here)
# =============================================================================

# Processed data: generated by build scripts, read by analysis scripts
output_data         <- here("data", "processed")

# Results
output_tables       <- here("results", "tables", "main")
output_tables_app   <- here("results", "tables", "appendix")
output_figures      <- here("results", "figures", "main")
output_figures_app  <- here("results", "figures", "appendix")
output_logs         <- here("results", "logs")

# =============================================================================
# OUTPUT file shortcuts  (written by 01_build/, read by 02_analysis/)
# =============================================================================

file_lrp_all        <- here("data", "processed", "lrp_all_years.csv")
file_lrp_iv         <- here("data", "processed", "lrp_with_iv.csv")
file_resid_premium  <- here("data", "processed", "residual_premium_weekly.csv")
file_county_panel   <- here("data", "processed", "county_panel_demand.csv")
file_gap_panel      <- here("data", "processed", "policy_panel_gap.csv")

# =============================================================================
# Create output folders if missing (safe to run every time)
# =============================================================================

invisible(lapply(
  c(output_data,
    output_tables, output_tables_app,
    output_figures, output_figures_app,
    output_logs),
  dir.create, showWarnings = FALSE, recursive = TRUE
))

message("Config loaded. Root: ", here())

# =============================================================================
# HELPER: check_inputs()
# Run this in Console any time to see what data files exist vs. are missing.
# =============================================================================

check_inputs <- function() {
  cat("=== Project root ===\n", here(), "\n\n")
  
  files <- list(
    "lrp_annual (2005-2026)" = file.path(input_lrp_annual, "lrp_2022.csv"),
    "feeder_cattle.csv"      = file_feeder,
    "fed_cattle.csv"         = file_fed,
    "GF.csv (futures)"       = file_gf,
    "LE.csv (futures)"       = file_le,
    "matched_with_iv.csv"    = file_matched_iv,
    "ZF_indemn_amt.xlsx"     = file_zf_gap,
    "OK_indemn_amt.xlsx"     = file_ok_gap,
    "usdm drought"           = file_drought,
    "cash_cattle_5area.csv"  = file_cash_price
  )
  
  cat("=== Input files ===\n")
  for (nm in names(files)) {
    status <- if (file.exists(files[[nm]])) "OK   " else "MISS "
    cat(status, nm, "\n      ->", files[[nm]], "\n")
  }
  
  cat("\n=== lrp_annual folder ===\n")
  if (dir.exists(input_lrp_annual)) {
    f <- list.files(input_lrp_annual, pattern = "\\.csv$")
    cat("Found", length(f), "csv files:",
        paste(head(f, 3), collapse=", "),
        if(length(f) > 3) paste0("... (", length(f), " total)") else "", "\n")
  } else {
    cat("FOLDER MISSING:", input_lrp_annual, "\n")
  }
  
  cat("\n=== Output folders ===\n")
  for (d in c(output_data, output_tables, output_figures, output_logs)) {
    cat(if (dir.exists(d)) "OK   " else "MISS ", d, "\n")
  }
}